image:
  repository: ghcr.io/mr-nuno/rabbitmq-ui
  tag: "1.0.5"
  pullPolicy: Always

replicas: 1
port: 80

env:
  TZ: Europe/Stockholm

rabbitmq:
  ip: "127.0.0.1"
  hostname: "rabbitmq.pew.local"
  url: "https://rabbitmq.pew.local"
  user: "guest"
  pass: "guest"

ingress:
  host: rmq-ui.pew.local
  tls:
    secretName: pew-wildcard-tls
