image:
  repository: ghcr.io/mr-nuno/rabbitmq-ui
  tag: "latest"
  pullPolicy: Always

replicas: 1
port: 80

env:
  TZ: Europe/Stockholm

rabbitmq:
  ip: "10.43.137.249"
  hostname: "rabbitmq.pew.local"

ingress:
  host: rmq-ui.pew.local
  tls:
    secretName: pew-wildcard-tls
