apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: gravitee-ui
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: gravitee-ui
  template:
    metadata:
      labels:
        app: gravitee-ui
    spec:
      containers:
        - name: gravitee-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: TZ
              value: {{ .Values.env.TZ }}
            - name: APIM_URL
              value: {{ .Values.apim.url }}
            - name: APIM_HOST
              value: {{ .Values.apim.host }}
